[build]
  builder = "dockerfile"
  dockerfilePath = "backend/Dockerfile"

[deploy]
  startCommand = "gunicorn crm.wsgi:application --bind 0.0.0.0:$PORT"

[env]
  DJANGO_SECRET_KEY = "super-secret-key"
  DEBUG = "False"