[build]
  builder = "dockerfile"
  dockerfilePath = "backend/Dockerfile"

[deploy]

  startCommand = "/bin/sh -c /start.sh"

[env]
  DJANGO_SECRET_KEY = "wvt&yv34ghyqcvhr3ikxqnoz821)1s2xgibkpm-y)wt_svwe@e"
  DEBUG = "False"